version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    container_name: shopapp_api
    ports:
      - "8000:8000"
    environment:
      # Add your AWS Public IP or Domain here, separated by commas
      # Example: http://localhost:8081,http://54.123.45.67:8081
      - CORS_ORIGINS=http://localhost:8081,http://127.0.0.1:8081
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      # Mounts the code for development (optional, remove for production)
      - ./api_gateway:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopapp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"